name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/deno        # see https://deno.land/manual/linking_to_external_code
          key: ${{ runner.os }}-deno # it seems there's no particular cache keying required
          restore-keys: |
            ${{ runner.os }}-gradle
      - run: |
          deno --version
          deno info

          ./build.sh
          
          cd test
          ./all.sh ../bin/unipipe