name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: "~1.9"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/deno        # see https://deno.land/manual/linking_to_external_code
          key: ${{ runner.os }}-deno # it seems there's no particular cache keying required
          restore-keys: |
            ${{ runner.os }}-deno
      - run: |
          deno --version
          deno info

          ./build.sh
          
          cd test
          ./all.sh ../bin/unipipe
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unipipe
          path: |
            bin/unipipe-*